import streamlit as st
from PIL import Image, ImageDraw
import io
import urllib.request
from datetime import datetime
import pytz

st.set_page_config(page_title="BEJIN Studio", page_icon="👕", layout="wide")

        "if 'cart' not in st.session_state:\n",
        "    st.session_state['cart'] = []\n",
        "if 'current_step' not in st.session_state:\n",
        "    st.session_state['current_step'] = \"Welcome Studio ✨\"\n",
        "\n",
        "# --- Helper function to fetch open-source emoji PNGs safely over HTTP ---\n",
        "@st.cache_data(show_spinner=False)\n",
        "def fetch_emoji_image(emoji_name):\n",
        "    emoji_urls = {\n",
        "        \"Cute Bear 🧸\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f43b.png\",\n",
        "        \"Pink Bow 🎀\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f380.png\",\n",
        "        \"Red Heart ❤️\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2764.png\",\n",
        "        \"Retro Star 🌟\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f31f.png\",\n",
        "        \"Fresh Clover 🍀\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f340.png\",\n",
        "        \"Cherries 🍒\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f352.png\",\n",
        "        \"Sparkles ✨\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2728.png\"\n",
        "    }\n",
        "    url = emoji_urls.get(emoji_name)\n",
        "    if url:\n",
        "        try:\n",
        "            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n",
        "            with urllib.request.urlopen(req, timeout=3) as response:\n",
        "                return Image.open(io.BytesIO(response.read())).convert(\"RGBA\")\n",
        "        except:\n",
        "            return None\n",
        "    return None\n",
        "\n",
        "# --- Mockup Engine (Accepts dynamic Text Size and Image Size parameters) ---\n",
        "def create_shirt_mockup(color_name, text, text_size, uploaded_file, img_size, emoji, pos=\"Center\"):\n",
        "    color_map = {\n",
        "        \"Classic White ⚪\": (255, 255, 255),\n",
        "        \"Pitch Black ⚫\": (30, 30, 30),\n",
        "        \"Navy Blue 🔵\": (20, 40, 80),\n",
        "        \"Deep Green 🟢\": (20, 60, 40)\n",
        "    }\n",
        "    bg_color = color_map.get(color_name, (255, 255, 255))\n",
        "    text_color = (255, 255, 255) if color_name not in [\"Classic White ⚪\"] else (50, 50, 50)\n",
        "\n",
        "    img = Image.new('RGB', (400, 400), (243, 242, 238)) # Aesthetic light grid background tint\n",
        "    draw = ImageDraw.Draw(img)\n",
        "\n",
        "    # Neckline\n",
        "    draw.ellipse([160, 30, 240, 70], fill=(225, 225, 225), outline=(210, 210, 210))\n",
        "\n",
        "    # Balanced Silhouette\n",
        "    shirt_points = [\n",
        "        (160, 50), (240, 50),      # Collar\n",
        "        (330, 90), (350, 150),     # Right Sleeve\n",
        "        (290, 150), (280, 360),    # Right Torso\n",
        "        (120, 360), (110, 150),    # Left Torso\n",
        "        (110, 150), (50, 150),     # Left Sleeve\n",
        "        (70, 90)                   # Left Shoulder\n",
        "    ]\n",
        "    draw.polygon(shirt_points, fill=bg_color, outline=(200, 200, 200), width=1)\n",
        "    draw.line([(120, 360), (280, 360)], fill=(210, 210, 210), width=2)\n",
        "\n",
        "    # Horizontal Alignment Logic\n",
        "    x_pos = 200\n",
        "    if pos == \"Left\": x_pos = 145\n",
        "    elif pos == \"Right\": x_pos = 255\n",
        "\n",
        "    # Vertical Layering (Emoji @ 105, Text @ 125, Logo @ 160)\n",
        "    if emoji and emoji != \"None\":\n",
        "        e_img = fetch_emoji_image(emoji)\n",
        "        if e_img:\n",
        "            try:\n",
        "                e_img.thumbnail((26, 26))\n",
        "                img.paste(e_img, (x_pos - e_img.width//2, 105 - e_img.height//2), e_img)\n",
        "            except: pass\n",
        "\n",
        "    if text:\n",
        "        draw.text((x_pos, 125), text, fill=text_color, anchor=\"mm\", font_size=int(text_size))\n",
        "\n",
        "    if uploaded_file:\n",
        "        try:\n",
        "            file_bytes = uploaded_file if isinstance(uploaded_file, bytes) else uploaded_file.read()\n",
        "            u_img = Image.open(io.BytesIO(file_bytes)).convert(\"RGBA\")\n",
        "            u_img.thumbnail((int(img_size), int(img_size))) # Modified to use dynamic img_size\n",
        "            img.paste(u_img, (x_pos - u_img.width//2, 160 - u_img.height//2), u_img)\n",
        "        except: pass\n",
        "\n",
        "    return img\n",
        "\n",
        "# --- Dynamic Calculation Engine (Base 25,000 | Emoji +2,000 | Logo +5,000) ---\n",
        "def calculate_item_price(item):\n",
        "    price = 25000\n",
        "    if item['f_emoji'] != \"None\": price += 2000\n",
        "    if item['f_img'] is not None: price += 5000\n",
        "    if item['b_emoji'] != \"None\": price += 2000\n",
        "    if item['b_img'] is not None: price += 5000\n",
        "    return price\n",
        "\n",
        "# --- Receipt Engine Updated to matching plm. studio color tones ---\n",
        "def generate_jpeg_receipt(cart):\n",
        "    total_qty = len(cart)\n",
        "    shipping_fee = 0 if total_qty >= 2 else 5000\n",
        "\n",
        "    receipt_height = 700 + (total_qty * 160)\n",
        "    receipt = Image.new('RGB', (1000, receipt_height), (250, 249, 246)) # Off-white aesthetic cream\n",
        "    draw = ImageDraw.Draw(receipt)\n",
        "\n",
        "    korea_tz = pytz.timezone('Asia/Seoul')\n",
        "    now = datetime.now(korea_tz)\n",
        "\n",
        "    order_date = now.strftime(\"%Y-%m-%d\")\n",
        "    order_time = now.strftime(\"%H:%M:%S\")\n",
        "\n",
        "    # Outer Border with Brand Color #2F3E2B (Dark Olive Green)\n",
        "    draw.rectangle([40, 40, 960, receipt_height - 40], outline=(47, 62, 43), width=3)\n",
        "\n",
        "    # Header Branding Text\n",
        "    draw.text((500, 110), \"BEJIN.studio\", fill=(47, 62, 43), anchor=\"mm\", font_size=46)\n",
        "    draw.text((500, 165), \"Design your own clothing, your own way.\", fill=(120, 130, 115), anchor=\"mm\", font_size=20)\n",
        "    draw.text((500, 110), \"BEJIN.studio\", fill=(47, 62, 43), anchor=\"mm\", font_size=46)\n",
        "    draw.text((500, 200), f\"Order Date: {order_date}  |  Time: {order_time}\", fill=(120, 130, 115), anchor=\"mm\", font_size=18)\n",
        "\n",
        "    y_pos = 240\n",
        "    subtotal_accum = 0\n",
        "\n",
        "    for i, item in enumerate(cart):\n",
        "        draw.line([(80, y_pos), (920, y_pos)], fill=(225, 230, 220), width=1)\n",
        "        y_pos += 20\n",
        "\n",
        "        thumb = create_shirt_mockup(item['color'], item['f_txt'], item['f_txt_size'], item['f_img'], item['f_img_size'], item['f_emoji'], item['f_pos']).resize((110, 110))\n",
        "        draw.rectangle([89, y_pos - 1, 201, y_pos + 111], outline=(210, 215, 205), width=1)\n",
        "        receipt.paste(thumb, (90, y_pos))\n",
        "\n",
        "        item_price = calculate_item_price(item)\n",
        "        subtotal_accum += item_price\n",
        "        clean_color = item['color'].split()[0]\n",
        "\n",
        "        draw.text((230, y_pos + 10), f\"BEJIN Custom Shirt Order // #0{i+1}\", fill=(47, 62, 43), font_size=26)\n",
        "        draw.text((230, y_pos + 45), f\"Size: {item['size']}  |  Color: {clean_color}  |  Front Size: {item['f_txt_size']}pt\", fill=(120, 130, 115), font_size=20)\n",
        "        draw.text((230, y_pos + 75), f\"Logo: {'Yes (+5k)' if item['f_img'] else 'No'}  |  Emoji: {'Yes (+2k)' if item['f_emoji']!='None' else 'No'}\", fill=(120, 130, 115), font_size=20)\n",
        "\n",
        "        draw.text((910, y_pos + 40), f\"{item_price:,} KRW\", fill=(47, 62, 43), anchor=\"ra\", font_size=26)\n",
        "        y_pos += 140\n",
        "\n",
        "    y_pos += 20\n",
        "    draw.line([(80, y_pos), (920, y_pos)], fill=(47, 62, 43), width=2)\n",
        "    y_pos += 40\n",
        "\n",
        "    draw.text((100, y_pos), \"Subtotal Amount\", fill=(120, 130, 115), font_size=24)\n",
        "    draw.text((900, y_pos), f\"{subtotal_accum:,} KRW\", fill=(47, 62, 43), anchor=\"ra\", font_size=24)\n",
        "\n",
        "    y_pos += 50\n",
        "    draw.text((100, y_pos), \"Shipping Fee\", fill=(120, 130, 115), font_size=24)\n",
        "    draw.text((900, y_pos), \"Complimentary\" if shipping_fee == 0 else f\"{shipping_fee:,} KRW\", fill=(47, 62, 43), anchor=\"ra\", font_size=24)\n",
        "\n",
        "    y_pos += 70\n",
        "    grand_total = subtotal_accum + shipping_fee\n",
        "\n",
        "    # Total Box matching bottom band style\n",
        "    draw.rectangle([80, y_pos, 920, y_pos + 75], fill=(47, 62, 43))\n",
        "    draw.text((110, y_pos + 38), \"TOTAL PAYMENT\", fill=(250, 249, 246), anchor=\"lm\", font_size=24)\n",
        "    draw.text((890, y_pos + 38), f\"{grand_total:,} KRW\", fill=(255, 255, 255), anchor=\"rm\", font_size=28)\n",
        "\n",
        "    return receipt\n",
        "\n",
        "def go_to_step(step_name):\n",
        "    st.session_state['current_step'] = step_name\n",
        "    st.rerun()\n",
        "\n",
        "# --- SIDEBAR ROUTING ---\n",
        "options = [\"Welcome Studio ✨\", \"Step 1: Design Workshop\", \"Step 2: Finalize Order\"]\n",
        "sidebar_selection = st.sidebar.radio(\"Navigation\", options, index=options.index(st.session_state['current_step']))\n",
        "if sidebar_selection != st.session_state['current_step']:\n",
        "    go_to_step(sidebar_selection)\n",
        "\n",
        "# --- WELCOME PAGE (WITH DYNAMIC PREVIEW GALLERY) ---\n",
        "if st.session_state['current_step'] == \"Welcome Studio ✨\":\n",
        "    # Header Banner Block matching BEJIN studio layout\n",
        "    st.markdown(\"\"\"\n",
        "        <div style=\"background-color: #FFFFFF; padding: 40px; border-radius: 20px; border: 1px solid #D1DCB2; margin-bottom: 30px;\">\n",
        "            <h1 style=\"margin: 0; font-size: 38px; color: #2F3E2B;\">[BEJIN] Your style. Your rules. Fully customized.</h1>\n",
        "            <p style=\"color: #6B7A64; font-size: 18px; margin-top: 10px;\">Design your own clothing, your own way.📮</p>\n",
        "        </div>\n",
        "    \"\"\", unsafe_allow_html=True)\n",
        "\n",
        "    col_info, col_action = st.columns([1.2, 1])\n",
        "    with col_info:\n",
        "        st.markdown(\"### ✨ STUDIO PROCESS\")\n",
        "        st.write(\"1. **Design a shirt** with unique color, text size, logo, and tiny emoji motifs.\")\n",
        "        st.write(\"2. Click **'🛒 Add This Design to Cart'** to lock your creation.\")\n",
        "        st.write(\"3. Instantly change parameters to design your **second or third shirt** completely from scratch.\")\n",
        "        st.write(\"4. Finalize to get a receipt.\")\n",
        "\n",
        "        st.markdown(\"### 💰 ADD ON PRICING\")\n",
        "        st.table({\n",
        "            \"Component Selection\": [\"Plain Shirt / Pure Text Base\", \"Emoji Graphic Accent\", \"Custom Logo Upload Image\"],\n",
        "            \"Price Rule (KRW)\": [\"25,000 KRW\", \"+ 2,000 KRW\", \"+ 5,000 KRW\"]\n",
        "        })\n",
        "        st.info(\"🔥 **PROMO:** Buy 2 shirts or more to unlock **FREE SHIPPING**!\")\n",
        "\n",
        "    with col_action:\n",
        "        st.markdown(\"### 🛒 LIVE CART PREVIEW\")\n",
        "\n",
        "        if not st.session_state['cart']:\n",
        "            st.info(\"Your cart is empty. Rendering minimalist default template as inspiration:\")\n",
        "            sample_shirt = create_shirt_mockup(\"Classic White ⚪\", \"studio.\", 20, None, 45, \"None\", \"Center\")\n",
        "            st.image(sample_shirt, width=280, caption=\"Sample: Plain White Studio Shirt\")\n",
        "        else:\n",
        "            st.success(f\"You have {len(st.session_state['cart'])} custom shirt(s) ready in your cart!\")\n",
        "\n",
        "            for idx, item in enumerate(st.session_state['cart']):\n",
        "                with st.expander(f\"👕 Shirt #{idx+1} Preview - {item['color'].split()[0]} ({item['size']})\", expanded=True):\n",
        "                    col_p1, col_p2 = st.columns(2)\n",
        "                    with col_p1:\n",
        "                        f_img_thumb = create_shirt_mockup(item['color'], item['f_txt'], item['f_txt_size'], item['f_img'], item['f_img_size'], item['f_emoji'], item['f_pos'])\n",
        "                        st.image(f_img_thumb, caption=f\"Front Look (Text: {item['f_txt_size']}pt)\", use_container_width=True)\n",
        "                    with col_p2:\n",
        "                        b_img_thumb = create_shirt_mockup(item['color'], item['b_txt'], item['b_txt_size'], item['b_img'], item['b_img_size'], item['b_emoji'], item['b_pos'])\n",
        "                        st.image(b_img_thumb, caption=f\"Back Look (Text: {item['b_txt_size']}pt)\", use_container_width=True)\n",
        "                    st.write(f\"**Value:** {calculate_item_price(item):,} KRW\")\n",
        "\n",
        "            if st.button(\"Clear Cart & Reset Previews\"):\n",
        "                st.session_state['cart'] = []\n",
        "                st.rerun()\n",
        "\n",
        "        st.markdown(\"<br>\", unsafe_allow_html=True)\n",
        "        if st.button(\"🛍️ START DESIGNING ➔\", type=\"primary\", use_container_width=True):\n",
        "            go_to_step(\"Step 1: Design Workshop\")\n",
        "\n",
        "# --- DESIGN WORKSHOP (WITH NEW FONT SIZE SLIDERS) ---\n",
        "elif st.session_state['current_step'] == \"Step 1: Design Workshop\":\n",
        "    st.header(f\"🎨 Step 1: Creative Canvas (Current Cart: {len(st.session_state['cart'])} Items)\")\n",
        "\n",
        "    col_basic, col_custom, col_preview = st.columns([1, 1.2, 1.5])\n",
        "\n",
        "    with col_basic:\n",
        "        st.markdown(\"### 1. Apparel Base\")\n",
        "        color = st.selectbox(\"Shirt Color\", [\"Classic White ⚪\", \"Pitch Black ⚫\", \"Navy Blue 🔵\", \"Deep Green 🟢\"])\n",
        "        size = st.select_slider(\"Size Config\", [\"S\", \"M\", \"L\", \"XL\"])\n",
        "\n",
        "        st.markdown(\"---\")\n",
        "        st.markdown(\"### 🛒 Cart Dashboard\")\n",
        "        if not st.session_state['cart']:\n",
        "            st.caption(\"No shirts added yet.\")\n",
        "        else:\n",
        "            for idx, c_item in enumerate(st.session_state['cart']):\n",
        "                st.caption(f\"#{idx+1}: {c_item['color'].split()[0]} ({c_item['size']}) - {calculate_item_price(c_item):,} KRW\")\n",
        "            if st.button(\"Reset All items\", key=\"reset_workshop\"):\n",
        "                st.session_state['cart'] = []\n",
        "                st.rerun()\n",
        "\n",
        "    with col_custom:\n",
        "        emojis = [\"None\", \"Cute Bear 🧸\", \"Pink Bow 🎀\", \"Red Heart ❤️\", \"Retro Star 🌟\", \"Fresh Clover 🍀\", \"Cherries 🍒\", \"Sparkles ✨\"]\n",
        "\n",
        "        # --- FRONT APP DESIGN CONTROLS ---\n",
        "        st.markdown(\"### 2. Front Parameters\")\n",
        "        f_pos = st.radio(\"Alignment\", [\"Left\", \"Center\", \"Right\"], horizontal=True, key='fp')\n",
        "        f_emoji = st.selectbox(\"Mini Emoji Accent (+2k)\", emojis, key='fe')\n",
        "        f_txt = st.text_input(\"Mini Text Graphic (Base)\", placeholder=\"Type minimalist tags...\", key='ft')\n",
        "        f_txt_size = st.slider(\"Front Text Size (pt)\", min_value=12, max_value=36, value=20, step=2, key='fts')\n",
        "        f_img = st.file_uploader(\"Logo Upload (+5k)\", type=['png','jpg'], key='f')\n",
        "        f_img_size = st.slider(\"Front Logo Size (px)\", min_value=20, max_value=100, value=45, step=5, key='fis') # New Image Size Slider\n",
        "\n",
        "        st.markdown(\"---\")\n",
        "\n",
        "        # --- BACK APP DESIGN CONTROLS ---\n",
        "        st.markdown(\"### 3. Back Parameters\")\n",
        "        b_pos = st.radio(\"Alignment \", [\"Left\", \"Center\", \"Right\"], horizontal=True, key='bp')\n",
        "        b_emoji = st.selectbox(\"Mini Emoji Accent (+2k) \", emojis, key='be')\n",
        "        b_txt = st.text_input(\"Mini Text Graphic (Base) \", placeholder=\"Type custom tags...\", key='bt')\n",
        "        b_txt_size = st.slider(\"Back Text Size (pt)\", min_value=12, max_value=36, value=20, step=2, key='bts')\n",
        "        b_img = st.file_uploader(\"Logo Upload (+5k) \", type=['png','jpg'], key='b')\n",
        "        b_img_size = st.slider(\"Back Logo Size (px)\", min_value=20, max_value=100, value=45, step=5, key='bis') # New Image Size Slider\n",
        "\n",
        "    with col_preview:\n",
        "        # --- REAL-TIME PREVIEW COLUMN (Stacked vertically in the right column) ---\n",
        "        st.markdown(\"### 🖼️ Front Real-Time Preview\")\n",
        "        st.image(create_shirt_mockup(color, f_txt, f_txt_size, f_img, f_img_size, f_emoji, f_pos), use_container_width=True)\n",
        "\n",
        "        st.markdown(\"### 🖼️ Back Real-Time Preview\")\n",
        "        st.image(create_shirt_mockup(color, b_txt, b_txt_size, b_img, b_img_size, b_emoji, b_pos), use_container_width=True)\n",
        "\n",
        "        current_item_temp = {\n",
        "            \"color\": color, \"size\": size,\n",
        "            \"f_txt\": f_txt, \"f_txt_size\": f_txt_size, \"f_img\": f_img.getvalue() if f_img else None, \"f_img_size\": f_img_size, \"f_pos\": f_pos, \"f_emoji\": f_emoji,\n",
        "            \"b_txt\": b_txt, \"b_txt_size\": b_txt_size, \"b_img\": b_img.getvalue() if b_img else None, \"b_img_size\": b_img_size, \"b_pos\": b_pos, \"b_emoji\": b_emoji\n",
        "        }\n",
        "\n",
        "        this_price = calculate_item_price(current_item_temp)\n",
        "        st.metric(\"Current Design Value\", f\"{this_price:,} KRW\")\n",
        "\n",
        "        col_btn1, col_btn2 = st.columns(2)\n",
        "        with col_btn1:\n",
        "            if st.button(\"🛒 Add This Design to Cart\", type=\"secondary\", use_container_width=True):\n",
        "                st.session_state['cart'].append(current_item_temp)\n",
        "                st.success(f\"Success! Shirt #{len(st.session_state['cart'])} added with size specifications.\")\n",
        "                st.rerun()\n",
        "\n",
        "        with col_btn2:\n",
        "            if st.button(\"✅ Checkout All Items ➔\", type=\"primary\", use_container_width=True):\n",
        "                if not st.session_state['cart'] and (f_txt or f_img or f_emoji != \"None\" or b_txt or b_img or b_emoji != \"None\"):\n",
        "                    st.session_state['cart'].append(current_item_temp)\n",
        "\n",
        "                if not st.session_state['cart']:\n",
        "                    st.error(\"Your cart is empty. Please add at least one design before checkout.\")\n",
        "                else:\n",
        "                    go_to_step(\"Step 2: Finalize Order\")\n",
        "\n",
        "# --- MULTI-ITEM DIGITAL RECEIPT ---\n",
        "elif st.session_state['current_step'] == \"Step 2: Finalize Order\":\n",
        "    st.header(\"🧾 Step 2: Finalize Order\")\n",
        "\n",
        "    if not st.session_state.get('cart'):\n",
        "        st.error(\"No active cart found. Please return to the Workshop.\")\n",
        "        if st.button(\"Back to Workshop\"): go_to_step(\"Step 1: Design Workshop\")\n",
        "    else:\n",
        "        st.balloons()\n",
        "        cart_data = st.session_state['cart']\n",
        "\n",
        "        col_receipt_view, col_receipt_meta = st.columns([1, 1])\n",
        "\n",
        "        with col_receipt_view:\n",
        "            final_receipt = generate_jpeg_receipt(cart_data)\n",
        "            st.image(final_receipt, width=450)\n",
        "\n",
        "        with col_receipt_meta:\n",
        "            st.markdown(\"### 🎉 Purchase Complete!\")\n",
        "            st.write(f\"Thank you for your order. We have successfully rendered a single receipt for all **{len(cart_data)} customized items** in your session.\")\n",
        "\n",
        "            img_buffer = io.BytesIO()\n",
        "            final_receipt.save(img_buffer, format='JPEG', quality=95)\n",
        "\n",
        "            st.markdown(\"<br>\", unsafe_allow_html=True)\n",
        "            st.download_button(\"📥 DOWNLOAD RECEIPT (.jpeg)\", data=img_buffer.getvalue(), file_name=\"BEJIN_studio_receipt.jpg\", mime=\"image/jpeg\", use_container_width=True)\n",
        "\n",
        "            if st.button(\"🔄 Design More Shirts (New Session)\", use_container_width=True):\n",
        "                st.session_state['cart'] = []\n",
        "                go_to_step(\"Step 1: Design Workshop\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ojevVyi6-1ib",
        "outputId": "dd6c8b06-162f-4ed7-96a8-f9ba31ce91da"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting app.py\n"
          ]
        }
      ]
    }
