{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMysG94VuBjlCAQaEEC6act",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/nwainwza/BEJIN.studio/blob/main/BEJIN_Custom_T_shirt.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Install Streamlit and pandas libraries\n",
        "!pip install streamlit\n",
        "!pip install pandas"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DoKuDqwvq4mp",
        "outputId": "9985e135-f568-4670-a47b-6d29428b1fbd"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)\n",
            "Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)\n",
            "Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)\n",
            "Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.47.0)\n",
            "Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)\n",
            "Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)\n",
            "Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.29)\n",
            "Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)\n",
            "Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.21.2)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.15)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.2/9.2 MB\u001b[0m \u001b[31m45.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m11.3/11.3 MB\u001b[0m \u001b[31m64.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.2 streamlit-1.58.0\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)\n",
            "Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile app.py\n",
        "import streamlit as st\n",
        "from PIL import Image, ImageDraw\n",
        "import io\n",
        "import urllib.request\n",
        "from datetime import datetime\n",
        "import pytz\n",
        "\n",
        "st.set_page_config(page_title=\"BEJIN Studio: Custon shirt Studio\", page_icon=\"👕\", layout=\"wide\")\n",
        "\n",
        "# --- Initialize Global Session States ---\n",
        "if 'cart' not in st.session_state:\n",
        "    st.session_state['cart'] = []\n",
        "if 'current_step' not in st.session_state:\n",
        "    st.session_state['current_step'] = \"Welcome Studio ✨\"\n",
        "\n",
        "# --- Helper function to fetch open-source emoji PNGs safely over HTTP ---\n",
        "@st.cache_data(show_spinner=False)\n",
        "def fetch_emoji_image(emoji_name):\n",
        "    emoji_urls = {\n",
        "        \"Cute Bear 🧸\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f43b.png\",\n",
        "        \"Pink Bow 🎀\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f380.png\",\n",
        "        \"Red Heart ❤️\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2764.png\",\n",
        "        \"Retro Star 🌟\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f31f.png\",\n",
        "        \"Fresh Clover 🍀\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f340.png\",\n",
        "        \"Cherries 🍒\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f352.png\",\n",
        "        \"Sparkles ✨\": \"https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2728.png\"\n",
        "    }\n",
        "    url = emoji_urls.get(emoji_name)\n",
        "    if url:\n",
        "        try:\n",
        "            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n",
        "            with urllib.request.urlopen(req, timeout=3) as response:\n",
        "                return Image.open(io.BytesIO(response.read())).convert(\"RGBA\")\n",
        "        except:\n",
        "            return None\n",
        "    return None\n",
        "\n",
        "# --- Mockup Engine (Accepts dynamic Text Size and Image Size parameters) ---\n",
        "def create_shirt_mockup(color_name, text, text_size, uploaded_file, img_size, emoji, pos=\"Center\"):\n",
        "    color_map = {\n",
        "        \"Classic White ⚪\": (255, 255, 255),\n",
        "        \"Pitch Black ⚫\": (30, 30, 30),\n",
        "        \"Navy Blue 🔵\": (20, 40, 80),\n",
        "        \"Deep Green 🟢\": (20, 60, 40)\n",
        "    }\n",
        "    bg_color = color_map.get(color_name, (255, 255, 255))\n",
        "    text_color = (255, 255, 255) if color_name not in [\"Classic White ⚪\"] else (50, 50, 50)\n",
        "\n",
        "    img = Image.new('RGB', (400, 400), (243, 242, 238)) # Aesthetic light grid background tint\n",
        "    draw = ImageDraw.Draw(img)\n",
        "\n",
        "    # Neckline\n",
        "    draw.ellipse([160, 30, 240, 70], fill=(225, 225, 225), outline=(210, 210, 210))\n",
        "\n",
        "    # Balanced Silhouette\n",
        "    shirt_points = [\n",
        "        (160, 50), (240, 50),      # Collar\n",
        "        (330, 90), (350, 150),     # Right Sleeve\n",
        "        (290, 150), (280, 360),    # Right Torso\n",
        "        (120, 360), (110, 150),    # Left Torso\n",
        "        (110, 150), (50, 150),     # Left Sleeve\n",
        "        (70, 90)                   # Left Shoulder\n",
        "    ]\n",
        "    draw.polygon(shirt_points, fill=bg_color, outline=(200, 200, 200), width=1)\n",
        "    draw.line([(120, 360), (280, 360)], fill=(210, 210, 210), width=2)\n",
        "\n",
        "    # Horizontal Alignment Logic\n",
        "    x_pos = 200\n",
        "    if pos == \"Left\": x_pos = 145\n",
        "    elif pos == \"Right\": x_pos = 255\n",
        "\n",
        "    # Vertical Layering (Emoji @ 105, Text @ 125, Logo @ 160)\n",
        "    if emoji and emoji != \"None\":\n",
        "        e_img = fetch_emoji_image(emoji)\n",
        "        if e_img:\n",
        "            try:\n",
        "                e_img.thumbnail((26, 26))\n",
        "                img.paste(e_img, (x_pos - e_img.width//2, 105 - e_img.height//2), e_img)\n",
        "            except: pass\n",
        "\n",
        "    if text:\n",
        "        draw.text((x_pos, 125), text, fill=text_color, anchor=\"mm\", font_size=int(text_size))\n",
        "\n",
        "    if uploaded_file:\n",
        "        try:\n",
        "            file_bytes = uploaded_file if isinstance(uploaded_file, bytes) else uploaded_file.read()\n",
        "            u_img = Image.open(io.BytesIO(file_bytes)).convert(\"RGBA\")\n",
        "            u_img.thumbnail((int(img_size), int(img_size))) # Modified to use dynamic img_size\n",
        "            img.paste(u_img, (x_pos - u_img.width//2, 160 - u_img.height//2), u_img)\n",
        "        except: pass\n",
        "\n",
        "    return img\n",
        "\n",
        "# --- Dynamic Calculation Engine (Base 25,000 | Emoji +2,000 | Logo +5,000) ---\n",
        "def calculate_item_price(item):\n",
        "    price = 25000\n",
        "    if item['f_emoji'] != \"None\": price += 2000\n",
        "    if item['f_img'] is not None: price += 5000\n",
        "    if item['b_emoji'] != \"None\": price += 2000\n",
        "    if item['b_img'] is not None: price += 5000\n",
        "    return price\n",
        "\n",
        "# --- Receipt Engine Updated to matching plm. studio color tones ---\n",
        "def generate_jpeg_receipt(cart):\n",
        "    total_qty = len(cart)\n",
        "    shipping_fee = 0 if total_qty >= 2 else 5000\n",
        "\n",
        "    receipt_height = 700 + (total_qty * 160)\n",
        "    receipt = Image.new('RGB', (1000, receipt_height), (250, 249, 246)) # Off-white aesthetic cream\n",
        "    draw = ImageDraw.Draw(receipt)\n",
        "\n",
        "    korea_tz = pytz.timezone('Asia/Seoul')\n",
        "    now = datetime.now(korea_tz)\n",
        "\n",
        "    order_date = now.strftime(\"%Y-%m-%d\")\n",
        "    order_time = now.strftime(\"%H:%M:%S\")\n",
        "\n",
        "    # Outer Border with Brand Color #2F3E2B (Dark Olive Green)\n",
        "    draw.rectangle([40, 40, 960, receipt_height - 40], outline=(47, 62, 43), width=3)\n",
        "\n",
        "    # Header Branding Text\n",
        "    draw.text((500, 110), \"BEJIN.studio\", fill=(47, 62, 43), anchor=\"mm\", font_size=46)\n",
        "    draw.text((500, 165), \"Design your own clothing, your own way.\", fill=(120, 130, 115), anchor=\"mm\", font_size=20)\n",
        "    draw.text((500, 110), \"BEJIN.studio\", fill=(47, 62, 43), anchor=\"mm\", font_size=46)\n",
        "    draw.text((500, 200), f\"Order Date: {order_date}  |  Time: {order_time}\", fill=(120, 130, 115), anchor=\"mm\", font_size=18)\n",
        "\n",
        "    y_pos = 240\n",
        "    subtotal_accum = 0\n",
        "\n",
        "    for i, item in enumerate(cart):\n",
        "        draw.line([(80, y_pos), (920, y_pos)], fill=(225, 230, 220), width=1)\n",
        "        y_pos += 20\n",
        "\n",
        "        thumb = create_shirt_mockup(item['color'], item['f_txt'], item['f_txt_size'], item['f_img'], item['f_img_size'], item['f_emoji'], item['f_pos']).resize((110, 110))\n",
        "        draw.rectangle([89, y_pos - 1, 201, y_pos + 111], outline=(210, 215, 205), width=1)\n",
        "        receipt.paste(thumb, (90, y_pos))\n",
        "\n",
        "        item_price = calculate_item_price(item)\n",
        "        subtotal_accum += item_price\n",
        "        clean_color = item['color'].split()[0]\n",
        "\n",
        "        draw.text((230, y_pos + 10), f\"BEJIN Custom Shirt Order // #0{i+1}\", fill=(47, 62, 43), font_size=26)\n",
        "        draw.text((230, y_pos + 45), f\"Size: {item['size']}  |  Color: {clean_color}  |  Front Size: {item['f_txt_size']}pt\", fill=(120, 130, 115), font_size=20)\n",
        "        draw.text((230, y_pos + 75), f\"Logo: {'Yes (+5k)' if item['f_img'] else 'No'}  |  Emoji: {'Yes (+2k)' if item['f_emoji']!='None' else 'No'}\", fill=(120, 130, 115), font_size=20)\n",
        "\n",
        "        draw.text((910, y_pos + 40), f\"{item_price:,} KRW\", fill=(47, 62, 43), anchor=\"ra\", font_size=26)\n",
        "        y_pos += 140\n",
        "\n",
        "    y_pos += 20\n",
        "    draw.line([(80, y_pos), (920, y_pos)], fill=(47, 62, 43), width=2)\n",
        "    y_pos += 40\n",
        "\n",
        "    draw.text((100, y_pos), \"Subtotal Amount\", fill=(120, 130, 115), font_size=24)\n",
        "    draw.text((900, y_pos), f\"{subtotal_accum:,} KRW\", fill=(47, 62, 43), anchor=\"ra\", font_size=24)\n",
        "\n",
        "    y_pos += 50\n",
        "    draw.text((100, y_pos), \"Shipping Fee\", fill=(120, 130, 115), font_size=24)\n",
        "    draw.text((900, y_pos), \"Complimentary\" if shipping_fee == 0 else f\"{shipping_fee:,} KRW\", fill=(47, 62, 43), anchor=\"ra\", font_size=24)\n",
        "\n",
        "    y_pos += 70\n",
        "    grand_total = subtotal_accum + shipping_fee\n",
        "\n",
        "    # Total Box matching bottom band style\n",
        "    draw.rectangle([80, y_pos, 920, y_pos + 75], fill=(47, 62, 43))\n",
        "    draw.text((110, y_pos + 38), \"TOTAL PAYMENT\", fill=(250, 249, 246), anchor=\"lm\", font_size=24)\n",
        "    draw.text((890, y_pos + 38), f\"{grand_total:,} KRW\", fill=(255, 255, 255), anchor=\"rm\", font_size=28)\n",
        "\n",
        "    return receipt\n",
        "\n",
        "def go_to_step(step_name):\n",
        "    st.session_state['current_step'] = step_name\n",
        "    st.rerun()\n",
        "\n",
        "# --- SIDEBAR ROUTING ---\n",
        "options = [\"Welcome Studio ✨\", \"Step 1: Design Workshop\", \"Step 2: Finalize Order\"]\n",
        "sidebar_selection = st.sidebar.radio(\"Navigation\", options, index=options.index(st.session_state['current_step']))\n",
        "if sidebar_selection != st.session_state['current_step']:\n",
        "    go_to_step(sidebar_selection)\n",
        "\n",
        "# --- WELCOME PAGE (WITH DYNAMIC PREVIEW GALLERY) ---\n",
        "if st.session_state['current_step'] == \"Welcome Studio ✨\":\n",
        "    # Header Banner Block matching BEJIN studio layout\n",
        "    st.markdown(\"\"\"\n",
        "        <div style=\"background-color: #FFFFFF; padding: 40px; border-radius: 20px; border: 1px solid #D1DCB2; margin-bottom: 30px;\">\n",
        "            <h1 style=\"margin: 0; font-size: 38px; color: #2F3E2B;\">[BEJIN] Your style. Your rules. Fully customized.</h1>\n",
        "            <p style=\"color: #6B7A64; font-size: 18px; margin-top: 10px;\">Design your own clothing, your own way.📮</p>\n",
        "        </div>\n",
        "    \"\"\", unsafe_allow_html=True)\n",
        "\n",
        "    col_info, col_action = st.columns([1.2, 1])\n",
        "    with col_info:\n",
        "        st.markdown(\"### ✨ STUDIO PROCESS\")\n",
        "        st.write(\"1. **Design a shirt** with unique color, text size, logo, and tiny emoji motifs.\")\n",
        "        st.write(\"2. Click **'🛒 Add This Design to Cart'** to lock your creation.\")\n",
        "        st.write(\"3. Instantly change parameters to design your **second or third shirt** completely from scratch.\")\n",
        "        st.write(\"4. Finalize to get a receipt.\")\n",
        "\n",
        "        st.markdown(\"### 💰 ADD ON PRICING\")\n",
        "        st.table({\n",
        "            \"Component Selection\": [\"Plain Shirt / Pure Text Base\", \"Emoji Graphic Accent\", \"Custom Logo Upload Image\"],\n",
        "            \"Price Rule (KRW)\": [\"25,000 KRW\", \"+ 2,000 KRW\", \"+ 5,000 KRW\"]\n",
        "        })\n",
        "        st.info(\"🔥 **PROMO:** Buy 2 shirts or more to unlock **FREE SHIPPING**!\")\n",
        "\n",
        "    with col_action:\n",
        "        st.markdown(\"### 🛒 LIVE CART PREVIEW\")\n",
        "\n",
        "        if not st.session_state['cart']:\n",
        "            st.info(\"Your cart is empty. Rendering minimalist default template as inspiration:\")\n",
        "            sample_shirt = create_shirt_mockup(\"Classic White ⚪\", \"studio.\", 20, None, 45, \"None\", \"Center\")\n",
        "            st.image(sample_shirt, width=280, caption=\"Sample: Plain White Studio Shirt\")\n",
        "        else:\n",
        "            st.success(f\"You have {len(st.session_state['cart'])} custom shirt(s) ready in your cart!\")\n",
        "\n",
        "            for idx, item in enumerate(st.session_state['cart']):\n",
        "                with st.expander(f\"👕 Shirt #{idx+1} Preview - {item['color'].split()[0]} ({item['size']})\", expanded=True):\n",
        "                    col_p1, col_p2 = st.columns(2)\n",
        "                    with col_p1:\n",
        "                        f_img_thumb = create_shirt_mockup(item['color'], item['f_txt'], item['f_txt_size'], item['f_img'], item['f_img_size'], item['f_emoji'], item['f_pos'])\n",
        "                        st.image(f_img_thumb, caption=f\"Front Look (Text: {item['f_txt_size']}pt)\", use_container_width=True)\n",
        "                    with col_p2:\n",
        "                        b_img_thumb = create_shirt_mockup(item['color'], item['b_txt'], item['b_txt_size'], item['b_img'], item['b_img_size'], item['b_emoji'], item['b_pos'])\n",
        "                        st.image(b_img_thumb, caption=f\"Back Look (Text: {item['b_txt_size']}pt)\", use_container_width=True)\n",
        "                    st.write(f\"**Value:** {calculate_item_price(item):,} KRW\")\n",
        "\n",
        "            if st.button(\"Clear Cart & Reset Previews\"):\n",
        "                st.session_state['cart'] = []\n",
        "                st.rerun()\n",
        "\n",
        "        st.markdown(\"<br>\", unsafe_allow_html=True)\n",
        "        if st.button(\"🛍️ START DESIGNING ➔\", type=\"primary\", use_container_width=True):\n",
        "            go_to_step(\"Step 1: Design Workshop\")\n",
        "\n",
        "# --- DESIGN WORKSHOP (WITH NEW FONT SIZE SLIDERS) ---\n",
        "elif st.session_state['current_step'] == \"Step 1: Design Workshop\":\n",
        "    st.header(f\"🎨 Step 1: Creative Canvas (Current Cart: {len(st.session_state['cart'])} Items)\")\n",
        "\n",
        "    col_basic, col_custom, col_preview = st.columns([1, 1.2, 1.5])\n",
        "\n",
        "    with col_basic:\n",
        "        st.markdown(\"### 1. Apparel Base\")\n",
        "        color = st.selectbox(\"Shirt Color\", [\"Classic White ⚪\", \"Pitch Black ⚫\", \"Navy Blue 🔵\", \"Deep Green 🟢\"])\n",
        "        size = st.select_slider(\"Size Config\", [\"S\", \"M\", \"L\", \"XL\"])\n",
        "\n",
        "        st.markdown(\"---\")\n",
        "        st.markdown(\"### 🛒 Cart Dashboard\")\n",
        "        if not st.session_state['cart']:\n",
        "            st.caption(\"No shirts added yet.\")\n",
        "        else:\n",
        "            for idx, c_item in enumerate(st.session_state['cart']):\n",
        "                st.caption(f\"#{idx+1}: {c_item['color'].split()[0]} ({c_item['size']}) - {calculate_item_price(c_item):,} KRW\")\n",
        "            if st.button(\"Reset All items\", key=\"reset_workshop\"):\n",
        "                st.session_state['cart'] = []\n",
        "                st.rerun()\n",
        "\n",
        "    with col_custom:\n",
        "        emojis = [\"None\", \"Cute Bear 🧸\", \"Pink Bow 🎀\", \"Red Heart ❤️\", \"Retro Star 🌟\", \"Fresh Clover 🍀\", \"Cherries 🍒\", \"Sparkles ✨\"]\n",
        "\n",
        "        # --- FRONT APP DESIGN CONTROLS ---\n",
        "        st.markdown(\"### 2. Front Parameters\")\n",
        "        f_pos = st.radio(\"Alignment\", [\"Left\", \"Center\", \"Right\"], horizontal=True, key='fp')\n",
        "        f_emoji = st.selectbox(\"Mini Emoji Accent (+2k)\", emojis, key='fe')\n",
        "        f_txt = st.text_input(\"Mini Text Graphic (Base)\", placeholder=\"Type minimalist tags...\", key='ft')\n",
        "        f_txt_size = st.slider(\"Front Text Size (pt)\", min_value=12, max_value=36, value=20, step=2, key='fts')\n",
        "        f_img = st.file_uploader(\"Logo Upload (+5k)\", type=['png','jpg'], key='f')\n",
        "        f_img_size = st.slider(\"Front Logo Size (px)\", min_value=20, max_value=100, value=45, step=5, key='fis') # New Image Size Slider\n",
        "\n",
        "        st.markdown(\"---\")\n",
        "\n",
        "        # --- BACK APP DESIGN CONTROLS ---\n",
        "        st.markdown(\"### 3. Back Parameters\")\n",
        "        b_pos = st.radio(\"Alignment \", [\"Left\", \"Center\", \"Right\"], horizontal=True, key='bp')\n",
        "        b_emoji = st.selectbox(\"Mini Emoji Accent (+2k) \", emojis, key='be')\n",
        "        b_txt = st.text_input(\"Mini Text Graphic (Base) \", placeholder=\"Type custom tags...\", key='bt')\n",
        "        b_txt_size = st.slider(\"Back Text Size (pt)\", min_value=12, max_value=36, value=20, step=2, key='bts')\n",
        "        b_img = st.file_uploader(\"Logo Upload (+5k) \", type=['png','jpg'], key='b')\n",
        "        b_img_size = st.slider(\"Back Logo Size (px)\", min_value=20, max_value=100, value=45, step=5, key='bis') # New Image Size Slider\n",
        "\n",
        "    with col_preview:\n",
        "        # --- REAL-TIME PREVIEW COLUMN (Stacked vertically in the right column) ---\n",
        "        st.markdown(\"### 🖼️ Front Real-Time Preview\")\n",
        "        st.image(create_shirt_mockup(color, f_txt, f_txt_size, f_img, f_img_size, f_emoji, f_pos), use_container_width=True)\n",
        "\n",
        "        st.markdown(\"### 🖼️ Back Real-Time Preview\")\n",
        "        st.image(create_shirt_mockup(color, b_txt, b_txt_size, b_img, b_img_size, b_emoji, b_pos), use_container_width=True)\n",
        "\n",
        "        current_item_temp = {\n",
        "            \"color\": color, \"size\": size,\n",
        "            \"f_txt\": f_txt, \"f_txt_size\": f_txt_size, \"f_img\": f_img.getvalue() if f_img else None, \"f_img_size\": f_img_size, \"f_pos\": f_pos, \"f_emoji\": f_emoji,\n",
        "            \"b_txt\": b_txt, \"b_txt_size\": b_txt_size, \"b_img\": b_img.getvalue() if b_img else None, \"b_img_size\": b_img_size, \"b_pos\": b_pos, \"b_emoji\": b_emoji\n",
        "        }\n",
        "\n",
        "        this_price = calculate_item_price(current_item_temp)\n",
        "        st.metric(\"Current Design Value\", f\"{this_price:,} KRW\")\n",
        "\n",
        "        col_btn1, col_btn2 = st.columns(2)\n",
        "        with col_btn1:\n",
        "            if st.button(\"🛒 Add This Design to Cart\", type=\"secondary\", use_container_width=True):\n",
        "                st.session_state['cart'].append(current_item_temp)\n",
        "                st.success(f\"Success! Shirt #{len(st.session_state['cart'])} added with size specifications.\")\n",
        "                st.rerun()\n",
        "\n",
        "        with col_btn2:\n",
        "            if st.button(\"✅ Checkout All Items ➔\", type=\"primary\", use_container_width=True):\n",
        "                if not st.session_state['cart'] and (f_txt or f_img or f_emoji != \"None\" or b_txt or b_img or b_emoji != \"None\"):\n",
        "                    st.session_state['cart'].append(current_item_temp)\n",
        "\n",
        "                if not st.session_state['cart']:\n",
        "                    st.error(\"Your cart is empty. Please add at least one design before checkout.\")\n",
        "                else:\n",
        "                    go_to_step(\"Step 2: Finalize Order\")\n",
        "\n",
        "# --- MULTI-ITEM DIGITAL RECEIPT ---\n",
        "elif st.session_state['current_step'] == \"Step 2: Finalize Order\":\n",
        "    st.header(\"🧾 Step 2: Finalize Order\")\n",
        "\n",
        "    if not st.session_state.get('cart'):\n",
        "        st.error(\"No active cart found. Please return to the Workshop.\")\n",
        "        if st.button(\"Back to Workshop\"): go_to_step(\"Step 1: Design Workshop\")\n",
        "    else:\n",
        "        st.balloons()\n",
        "        cart_data = st.session_state['cart']\n",
        "\n",
        "        col_receipt_view, col_receipt_meta = st.columns([1, 1])\n",
        "\n",
        "        with col_receipt_view:\n",
        "            final_receipt = generate_jpeg_receipt(cart_data)\n",
        "            st.image(final_receipt, width=450)\n",
        "\n",
        "        with col_receipt_meta:\n",
        "            st.markdown(\"### 🎉 Purchase Complete!\")\n",
        "            st.write(f\"Thank you for your order. We have successfully rendered a single receipt for all **{len(cart_data)} customized items** in your session.\")\n",
        "\n",
        "            img_buffer = io.BytesIO()\n",
        "            final_receipt.save(img_buffer, format='JPEG', quality=95)\n",
        "\n",
        "            st.markdown(\"<br>\", unsafe_allow_html=True)\n",
        "            st.download_button(\"📥 DOWNLOAD RECEIPT (.jpeg)\", data=img_buffer.getvalue(), file_name=\"BEJIN_studio_receipt.jpg\", mime=\"image/jpeg\", use_container_width=True)\n",
        "\n",
        "            if st.button(\"🔄 Design More Shirts (New Session)\", use_container_width=True):\n",
        "                st.session_state['cart'] = []\n",
        "                go_to_step(\"Step 1: Design Workshop\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ojevVyi6-1ib",
        "outputId": "dd6c8b06-162f-4ed7-96a8-f9ba31ce91da"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting app.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# 1. Download and install Cloudflare Tunnel\n",
        "!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared\n",
        "!chmod +x cloudflared\n",
        "!mv cloudflared /usr/local/bin/\n",
        "\n",
        "# 2. Check the version to ensure successful installation\n",
        "print(\"--- Cloudflare Version ---\")\n",
        "!/usr/local/bin/cloudflared --version\n",
        "\n",
        "# 3. Run Streamlit using port 8502 with upload limits fixed\n",
        "!streamlit run app.py --server.port 8502 --server.maxUploadSize=500 &>/dev/null&\n",
        "\n",
        "# 4. Open a secure tunnel to port 8502\n",
        "print(\"\\n--- Website is launching... Please look for the link ending with '.trycloudflare.com' below ---\")\n",
        "!/usr/local/bin/cloudflared tunnel --url http://localhost:8502"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "O9CZkWdPq-9-",
        "outputId": "9033cc42-dd48-4858-89aa-fe9a629fcc3b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--- Cloudflare Version ---\n",
            "cloudflared version 2026.5.2 (built 2026-05-27-10:38 UTC)\n",
            "\n",
            "--- Website is launching... Please look for the link ending with '.trycloudflare.com' below ---\n",
            "\u001b[90m2026-05-29T14:56:27Z\u001b[0m \u001b[32mINF\u001b[0m Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps\n",
            "\u001b[90m2026-05-29T14:56:27Z\u001b[0m \u001b[32mINF\u001b[0m Requesting new quick Tunnel on trycloudflare.com...\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m +--------------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m |  https://switched-satisfaction-civil-big.trycloudflare.com                                 |\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m +--------------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Version 2026.5.2 (Checksum 5286698547f03df745adb2355f04c12dde52ef425491e81f433642d695521886)\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m GOOS: linux, GOVersion: go1.26.3, GoArch: amd64\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Settings: map[ha-connections:1 protocol:quic url:http://localhost:8502]\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configure-tunnels/local-management/as-a-service/\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Generated Connector ID: 2f1bbafa-ec22-4c38-908d-c3bb69ea86b1\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Initial protocol quic\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use 172.28.0.12 as source for IPv4\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use ::1 in zone lo as source for IPv6\n",
            "2026/05/29 14:56:31 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use 172.28.0.12 as source for IPv4\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m ICMP proxy will use ::1 in zone lo as source for IPv6\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Starting metrics server on 127.0.0.1:20241/metrics\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] \u001b[36mconnIndex=\u001b[0m0 \u001b[36mevent=\u001b[0m0 \u001b[36mip=\u001b[0m198.41.200.73\n",
            "\u001b[90m2026-05-29T14:56:31Z\u001b[0m \u001b[32mINF\u001b[0m Registered tunnel connection \u001b[36mconnIndex=\u001b[0m0 \u001b[36mconnection=\u001b[0m3c33948e-c640-45d4-bd69-a7a4fbadb73f \u001b[36mevent=\u001b[0m0 \u001b[36mip=\u001b[0m198.41.200.73 \u001b[36mlocation=\u001b[0matl13 \u001b[36mprotocol=\u001b[0mquic\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m +-------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |                               CONNECTIVITY PRE-CHECKS                               |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m +-------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  COMPONENT         TARGET                     STATUS  DETAILS                       |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |                                                                                     |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m +-------------------------------------------------------------------------------------+\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"DNS Resolution\" \u001b[36mdetails=\u001b[0m\"DNS Resolved successfully\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion1.v2.argotunnel.com\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"DNS Resolution\" \u001b[36mdetails=\u001b[0m\"DNS Resolved successfully\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion2.v2.argotunnel.com\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"UDP Connectivity\" \u001b[36mdetails=\u001b[0m\"QUIC connection successful\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion1.v2.argotunnel.com\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"UDP Connectivity\" \u001b[36mdetails=\u001b[0m\"QUIC connection successful\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion2.v2.argotunnel.com\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"TCP Connectivity\" \u001b[36mdetails=\u001b[0m\"HTTP/2 connection successful\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion1.v2.argotunnel.com\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"TCP Connectivity\" \u001b[36mdetails=\u001b[0m\"HTTP/2 connection successful\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mregion2.v2.argotunnel.com\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck \u001b[36mcomponent=\u001b[0m\"Cloudflare API\" \u001b[36mdetails=\u001b[0m\"API is reachable\" \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36mstatus=\u001b[0mpass \u001b[36mtarget=\u001b[0mapi.cloudflare.com:443\n",
            "\u001b[90m2026-05-29T14:56:37Z\u001b[0m \u001b[32mINF\u001b[0m precheck complete \u001b[36mhard_fail=\u001b[0mfalse \u001b[36mrun_id=\u001b[0md92ae1ac-f409-40f1-b40c-678711e68185 \u001b[36msuggested_protocol=\u001b[0mquic\n"
          ]
        }
      ]
    }
  ]
}